### ISSUE TITLE
Creating/overriding doesn't work

### ISSUE THREAD

**Issue by xbony2** [FTB-Gamepedia/Tilesheets#79] opened 2017-10-27 00:41 UTC
```
[bfaae93764196358485ec17a] /Special:CreateTileSheet TypeError from line 493 of /home/hydra/stable_public_html/includes/logging/LogEntry.php: Argument 1 passed to ManualLogEntry::setPerformer() must be an instance of User, string given, called in /home/hydra/stable_public_html/extensions/Tilesheets/special/SheetManager.php on line 96

Backtrace:

#0 /home/hydra/stable_public_html/extensions/Tilesheets/special/SheetManager.php(96): ManualLogEntry->setPerformer(string)
#1 /home/hydra/stable_public_html/extensions/Tilesheets/special/CreateTileSheet.php(72): SheetManager::deleteEntry(string, string)
#2 /home/hydra/stable_public_html/includes/specialpage/SpecialPage.php(522): CreateTileSheet->execute(NULL)
#3 /home/hydra/stable_public_html/includes/specialpage/SpecialPageFactory.php(578): SpecialPage->run(NULL)
#4 /home/hydra/stable_public_html/includes/MediaWiki.php(287): SpecialPageFactory::executePath(Title, RequestContext)
#5 /home/hydra/stable_public_html/includes/MediaWiki.php(862): MediaWiki->performRequest()
#6 /home/hydra/stable_public_html/includes/MediaWiki.php(523): MediaWiki->main()
#7 /home/hydra/stable_public_html/index.php(43): MediaWiki->run()
#8 {main}
```

Pressed "Override existing" with mod name "B" and standard tilesheet sizes and "0 0 Miner's Ring" in the import data. The difference is that I added the 16x tilesheet.

**Comment by elifoster** [comment] 2017-10-27 00:43
Duplicate of #74 

Resolved in next version

For that specific case, if none of the tiles are changed you can just edit the sheet using the SheetManager

**Closed by elifoster** 2017-10-27 00:43 UTC
Labels: bug, duplicate, special

**Comment by xbony2** [comment] 2017-10-27 00:44
works now :+1:

**Comment by elifoster** [comment] 2017-10-27 19:34
What do you mean? The CreateTileSheet overwrite option surely doesn't work because Tilesheets hasn't been updated.

**Comment by xbony2** [comment] 2017-10-27 23:35
editing the sheet through SheetManager
